### ISSUE TITLE
电信余额提醒脚本执行后出现错误提示

### ISSUE THREAD

**Issue by lkmnuiss** [id77/QuantumultX#2]
通知提示cookie获取成功，但是boxjs里面的session示出现内容。手动执行任务后，通知会出现错误的提示。

![image](https://user-images.githubusercontent.com/42618989/93618835-63405980-fa0a-11ea-8d12-a9ff5b207e93.jpeg)

**Comment by lkmnuiss** [comment]
请问如下内容是否正常；
{"url":"https://e.189.cn/store/user/balance_new.do?t=wechat","headers":{"Accept-Encoding":"gzip, deflate, br","Cookie":"CZSSON=e671556918fda1d42e47c115763c47b8f0bc05aa8d987896b655d6e2d27c4a92062444b970967a460965631421be0c66de00c319679f57ad16295f5e347bf02cc9b21332e168ff791a9c13230a9fd0f4d0a65b8fcac753c9bd1e7bffe49ee854f027987dc4718aae79fc7d27f51ad276d946ca4c49a02c9245e6ad9352e907047ed9fbfa387c428bab6efb4b4f46b8e67065952997bf23b4bbe1febd2d265095; __cookie4mobile=7A5E4254B85A4CE8CD862B127397D16927B5CEFFDD32263CEA1953A700793672D24B621AC127853B4451E097526B2796D25136690BF08A8518208B74D0174AF063DC174CC0577CEBE6E38D7A1DDF9FF6273EAF9ED47BBBB1; JSESSIONID=aaaWo10lWwufId3iCUBsx; apm_sid=09821A7181BFDCD4CDDF01B81672E401; apm_ct=20200914111723755; apm_ip=3C7F882534E8AE09FB6F822267563579E18E34ED; apm_ua=5CC43925DAE9FA1D7B2D0D8C3E51B795; apm_uid=E442AF5844095A6719C8DB59E5A2F33F","Connection":"keep-alive","Referer":"https://e.189.cn/store/wap/partner/stylehead/wechat.do?css=client","Accept":"application/json, text/javascript, */*; q=0.01","Host":"e.189.cn","User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/7.0.15(0x17000f2d) NetType/4G Language/en","Accept-Language":"en-us","X-Requested-With":"XMLHttpRequest"}}

**Comment by id77** [comment]
你好，好像接口返回的数据，每个人的账号存在差异；如果想要正常运行，麻烦提供返回数据，我会进行适配

**Comment by lkmnuiss** [comment]
返回数据在哪里获取？

Sent from my iPhone

On Sep 19, 2020, at 08:52, 小孩子不可以打架 <notifications@github.com> wrote:

﻿

你好，好像接口返回的数据，每个人的账号存在差异；如果想要正常运行，麻烦提供返回数据，我会进行适配

**Comment by id77** [comment]
我用你上面的会话获取结果，已经适配了，你更新试试

**Comment by xiazhijueju** [comment]
更新了任务脚本的远程订阅链接，进入到小程序同样是获得cookie，然后执行任务脚本，还是同之前一样出现下图所示
[cid:F8D50266-AA7A-41D8-8CB4-045EBDF2A07E-L0-001]

Sent from my iPhone

On Sep 19, 2020, at 09:19, 小孩子不可以打架 <notifications@github.com> wrote:

﻿

我用你上面的会话获取结果，已经适配了，你更新试试

**Comment by lkmnuiss** [comment]
更新了任务脚本的远程订阅链接，进入到小程序同样是获得cookie，然后执行任务脚本，还是同之前一样出现下图所示
![image](https://user-images.githubusercontent.com/42618989/93656261-95c67280-fa5b-11ea-92fc-f6326a17f913.jpeg)

**Comment by id77** [comment]
> 更新了任务脚本的远程订阅链接，进入到小程序同样是获得cookie，然后执行任务脚本，还是同之前一样出现下图所示
> ![image](https://user-images.githubusercontent.com/42618989/93656261-95c67280-fa5b-11ea-92fc-f6326a17f913.jpeg)

可能github资源有缓存，试多几次

**Comment by id77** [comment]
另外补充一点，这个task，唯有设定「提醒最低余额」，等于或小于这个值，才会有通知。
![image](https://user-images.githubusercontent.com/9592236/93657358-cfe84200-fa64-11ea-868a-57b5c98cc106.png)![image](https://user-images.githubusercontent.com/9592236/93657362-d70f5000-fa64-11ea-972d-09d86f77e292.png)

**Comment by lkmnuiss** [comment]
谢谢大佬，给你添麻烦了，目前手动执行任务通知显示已经正常了。

**Comment by lkmnuiss** [comment]
你好，脚本自动执行出现截图所示报错。然后重新启用cookie脚本来获取ck，未有通知提示获取ck成功。之后将boxjs里的session的内容删除，重新进入公众号获取ck，仍旧没有成功的通知，执行脚本，提示未找到ck。
![C57B49FB-8DBD-4ACB-A530-3F0C203B909A](https://user-images.githubusercontent.com/42618989/94227066-e17d8e00-ff2b-11ea-8870-d81c5a4003e2.jpeg)

**Comment by id77** [comment]
> 你好，脚本自动执行出现截图所示报错。然后重新启用cookie脚本来获取ck，未有通知提示获取ck成功。之后将boxjs里的session的内容删除，重新进入公众号获取ck，仍旧没有成功的通知，执行脚本，提示未找到ck。
> 
> ![C57B49FB-8DBD-4ACB-A530-3F0C203B909A](https://user-images.githubusercontent.com/42618989/94227066-e17d8e00-ff2b-11ea-8870-d81c5a4003e2.jpeg)
> 
> 

你这个图的提示，说明cookie失效了，用户未登录。
获取cookie失败，你要自己分析原因，可能是没有命中重写。如果没有命中重写：
- 可能是你配置的问题，检测hostname和rewrite，查看流量是否走cookie脚本，根据自己所用软件进行操作，如果你不会，我帮不了你，这些功能运用，你自己找路子学。
- 可能是用户的url不一样，这个需要你抓包，提供有效信息给我，我进行兼容。这个可能性小，如果你之前都能正常获取cookie，我觉得可以排除这项。

出现获取cookie无任何提示的情况，建议自己先排查。

**Comment by lkmnuiss** [comment]
不好意思，检查了一下，发现是e.189.com不在了，重新填写后，已经可以了。

发自我的iPhone

在 2020年9月25日，15:08，小孩子不可以打架 <notifications@github.com> 写道：

﻿

你好，脚本自动执行出现截图所示报错。然后重新启用cookie脚本来获取ck，未有通知提示获取ck成功。之后将boxjs里的session的内容删除，重新进入公众号获取ck，仍旧没有成功的通知，执行脚本，提示未找到ck。

[C57B49FB-8DBD-4ACB-A530-3F0C203B909A]<https://user-images.githubusercontent.com/42618989/94227066-e17d8e00-ff2b-11ea-8870-d81c5a4003e2.jpeg>

你这个图的提示，说明cookie失效了，用户未登录。
获取cookie失败，你要自己分析原因，可能是没有命中重写。如果没有命中重写：

  *   可能是你配置的问题，检测hostname和rewrite，查看流量是否走cookie脚本，根据自己所用软件进行操作，如果你不会，我帮不了你，这些功能运用，你自己找路子学。
  *   可能是用户的url不一样，这个需要你抓包，提供有效信息给我，我进行兼容。这个可能性小，如果你之前都能正常获取cookie，我觉得可以排除这项。

出现获取cookie无任何提示的情况，建议自己先排查。
