### ISSUE TITLE
感谢大佬的知乎脚本，太好用了！不知道大佬有没有可能做一个类似的贴吧、豆瓣脚本🤩

### ISSUE THREAD

**Issue by ArsenicX** [id77/QuantumultX#4]
贴吧、豆瓣小组的手机版和知乎一样，只能看最上面的几条回复，多了就强制跳转app，属实难看
希望大佬能做个类似的，不跳转app就能看完整回复的脚本，麻烦您了🤩🥺

**Comment by id77** [comment]
没在用贴吧哦，豆瓣用App，主要是聊天接收推送通知，没用网页。不考虑去花时间做。

**Comment by ArsenicX** [comment]
> 没在用贴吧哦，豆瓣用App，主要是聊天接收推送通知，没用网页。不考虑去花时间做。

好吧谢谢😭
