### ISSUE TITLE
jd_hd 中文pt_pin有问题

### ISSUE THREAD

**Issue by qhq** [id77/QuantumultX#5]
您好
使用jd_hd的时候发现，如果是中文的pt_pin，切换后会提示登录。
非中文的正常

**Comment by id77** [comment]
pin是不能改的，pin是用户id，不是昵称。本脚本没有备注，不想搞复杂，不想额外配置。

**Comment by qhq** [comment]
对的，pin是用户id，我意思就是切换的时候，如果是中文id的切换过去会丢失登录状态的。非中文的就正常显示切换后ck的账户的信息。
pt_pin=git;
pt_pin=%E7%8E%8B%E8%80%81%E8%99%8E;
比如git这个id的切换就正常，下面这个切换后，就会提示让你登录。
不知道是bug，还是就是这样的。

**Comment by id77** [comment]
我跟你说，pin不可能是中文，你自己的问题

**Comment by qhq** [comment]
![微信图片_20210609212719](https://user-images.githubusercontent.com/3319385/121363976-f7bc6480-c969-11eb-83bc-2d0b20f6b73c.jpg)
![微信图片_20210609212724](https://user-images.githubusercontent.com/3319385/121363985-f8ed9180-c969-11eb-8a17-0a3f1d9d8f93.jpg)

不知道我理解的pin对不对

**Comment by qhq** [comment]
后期京东注册的账号是默认随机字符，早期的京东号是可以自定义的，所以有短号，有中文。

**Comment by id77** [comment]
那我也没办法测试，我没这种账号，也是第一次见。我自己模拟并不能知道是否可行。
