### ISSUE TITLE
无忧行ac签到的问题

### ISSUE THREAD

**Issue by iptag** [id77/QuantumultX#7]
大佬，把你的jegotrip脚本稍微改了下，可以ac运行，并且我可以确定ACCOUNT_ID，USER_ID，MOBILE，TOKEN，TASK_ID都正确抓到包，并且正确写进了secrets。但每次运行都提示以下错误，我是用模拟器抓包，感觉有时在模拟器中打开无忧行时，getUserAssets页面（也就是任务中心页面）时而能显示正确的无忧币，时而显示无忧币数量为0，不知道这个问题该如何解决，还请指导一下

🔔无忧行, 开始!
{"result":true,"msg":null,"rtn":{"tasks":{"日常任务":[{"id":"***","name":"每日签到奖励","type":"日常","status":"上线","execType":"动作触发","triggerAction":"已签到","activeType":"自动激活","sendType":"自动发放","keyword":"qd","category":null,"createAt":1588385895000,"startTime":1525104000000,"endTime":1640966399000,"maxType":null,"maxCredits":0,"credits":8,"desc":"每日登录无忧行可以获得登录奖励。首次签到奖励5无忧币，连续签到每日增加1枚，10枚封顶；中途断签将重新从5枚开始；每月1号自动断签。"}]}}}

视频任务成功🎉
VideoTask body: 
{"code":200,"data":"update success","mes":"ok"}

兑换失败‼️
Exchange body: 
{"code":2002,"mes":"获取无忧行数据失败"}

getUserAssets body: 
{"code":"429","msg":"传入的token 不正确或已过期","body":{}}
无忧行

签到失败：今日已签到‼️ 无忧币 +8
视频任务：获取无忧行数据失败‼️
无忧币总计：undefined💰

🔔无忧行, 结束! 🕛 4.008 秒

**Comment by id77** [comment]
不予解决ac的问题，我反对使用ac跑脚本。

服务器都明确给出提示了，你自己的问题。

**Comment by id77** [comment]
不建议使用ac，会封禁账号。
而且你的问题很可能是各种不同ip导致的令牌失效。
